---
extends: default

# See: https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    min-spaces-from-content: 1
    # quoted-strings: # See: https://stackoverflow.com/a/69850618/10928938
  line-length:
    max: 200 # for URL
