arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
header: "import 'package:intl/intl.dart' as intl; // this is workaround. See: https://github.com/sensuikan1973/pedax/pull/122/checks?check_run_id=2364071229"
