---
# See: https://docs.flutter.dev/accessibility-and-localization/internationalization#adding-your-own-localized-messages

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false # See: https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
output-dir: lib/l10n # https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#configuring-the-l10n-yaml-file
