---
# See: https://docs.flutter.dev/accessibility-and-localization/internationalization#adding-your-own-localized-messages

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
