# See: https://dart.dev/tools/pub/pubspec

name: pedax
description: edax-reversi Board.
publish_to: 'none'
homepage: https://github.com/sensuikan1973/pedax # TODO: change to blanding site
repository: https://github.com/sensuikan1973/pedax
issue_tracker: https://github.com/sensuikan1973/pedax/issues

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment: # See: https://dart.dev/tools/pub/pubspec#sdk-constraints
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ^1.26.0-0

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  libedax4dart: ^0.3.0-beta.1
  package_info: ^0.5.0-nullsafety
  path_provider: ^1.6.27 # See: https://flutter.dev/docs/cookbook/persistence/reading-writing-files
  provider: ^5.0.0-nullsafety.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.7
  pedantic_sensuikan1973: any

flutter:
  uses-material-design: true
  generate: true # See: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages

  # See: https://flutter.dev/docs/development/ui/assets-and-images
  assets:
    - assets/
    - assets/libedax/data/
    - assets/libedax/dll/
