---
# See: https://dart.dev/tools/pub/pubspec

name: pedax
description: Reversi Board with edax.
publish_to: none
homepage: https://sensuikan1973.github.io/pedax/
repository: https://github.com/sensuikan1973/pedax
issue_tracker: https://github.com/sensuikan1973/pedax/issues

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# NOTE: you can't specify duplicated build number.
# See: https://appstoreconnect.apple.com/apps/1557500142/buildactivity
version: 6.18.0+114

environment: # See: https://dart.dev/tools/pub/pubspec#sdk-constraints
  sdk: ">=3.0.6 <4.0.0"
  flutter: ^3.10.6 # See: https://flutter.dev/docs/development/tools/sdk/releases

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  # See: https://github.com/google/flutter-desktop-embedding/tree/master/plugins/file_selector
  file_selector: ^1.0.0
  file_selector_linux: ^0.9.1+3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  intl: any # https://docs.flutter.dev/accessibility-and-localization/internationalization#adding-your-own-localized-messages
  libedax4dart: ^7.3.0
  logger: ^2.0.1
  macos_secure_bookmarks: ^0.2.1
  meta: ^1.9.1
  package_info_plus: ^4.0.2
  pasteboard: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.0.15 # See: https://flutter.dev/docs/cookbook/persistence/reading-writing-files
  provider: ^6.0.5
  sentry_flutter: ^7.7.0
  shared_preferences: ^2.1.2
  window_manager: ^0.3.4 # for "onWindowResize" and "onWindowMoved"
  window_size:
    git:
      # See: https://github.com/google/flutter-desktop-embedding/tree/main/plugins/window_size
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      # https://dart.dev/tools/pub/dependencies#git-packages
      ref: main

dev_dependencies:
  cider: ^0.2.1
  file_selector_platform_interface: ^2.5.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^3.14.2
  path_provider_platform_interface: ^2.0.6
  pedantic_sensuikan1973: ^5.2.0
  plugin_platform_interface: ^2.1.4
  # https://pub.dev/packages/shared_preferences_platform_interface/changelog#220
  # https://github.com/sensuikan1973/pedax/pull/1387#issuecomment-1489619974
  shared_preferences_platform_interface: ^2.2.0

flutter:
  uses-material-design: true
  generate: true # See: https://docs.flutter.dev/accessibility-and-localization/internationalization#adding-your-own-localized-messages

  # See: https://flutter.dev/docs/development/ui/assets-and-images
  assets:
    - assets/images/
    - assets/libedax/data/
    - assets/libedax/dll/

# windows desktop app is not sandboxed
# - https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
# - https://learn.microsoft.com/ja-jp/windows/msix/desktop/desktop-to-uwp-behind-the-scenes
msix_config: # See: https://pub.dev/packages/msix#-configuring-your-installer
  store: true
  display_name: pedax
  publisher_display_name: Naoki Shimizu
  identity_name: 1781NaokiShimizu.pedax
  publisher: CN=4CCE9711-39B6-4ECC-AA74-A350014A69B0
  languages: en, ja
  logo_path: assets/images/pedax_logo.png
  architecture: x64
