# See: https://dart.dev/tools/pub/pubspec

name: pedax
description: Reversi Board with edax.
publish_to: "none"
homepage: https://sensuikan1973.github.io/pedax/
repository: https://github.com/sensuikan1973/pedax
issue_tracker: https://github.com/sensuikan1973/pedax/issues

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# NOTE: you can't specify duplicated build number.
# See: https://appstoreconnect.apple.com/apps/1557500142/buildactivity
version: 1.8.0+24

environment: # See: https://dart.dev/tools/pub/pubspec#sdk-constraints
  sdk: ">=2.15.0-0 <3.0.0"
  flutter: ^2.7.0-0 # See: https://flutter.dev/docs/development/tools/sdk/releases

dependencies:
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  # See: https://github.com/google/flutter-desktop-embedding/tree/master/plugins/file_selector
  file_selector: ^0.8.2+1
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.0.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0 # Use the pinned version from flutter_localizations
  libedax4dart: ^2.1.0
    # git:
    #   url: https://github.com/sensuikan1973/libedax4dart.git
    #   branch: xxx
  logger: ^1.1.0
  macos_secure_bookmarks: ^0.2.0
  meta: ^1.7.0
  path: ^1.8.0
  path_provider: ^2.0.6 # See: https://flutter.dev/docs/cookbook/persistence/reading-writing-files
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  window_size:
    git:
      # See: https://github.com/google/flutter-desktop-embedding/tree/master/plugins/window_size
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^2.6.2
  pedantic_sensuikan1973: ^2.5.0

flutter:
  uses-material-design: true
  generate: true # See: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages

  # See: https://flutter.dev/docs/development/ui/assets-and-images
  assets:
    - assets/images/
    - assets/libedax/data/
    - assets/libedax/dll/

msix_config: # See: https://pub.dev/packages/msix#mag-configuration-optional
  store: true # See: https://pub.dev/packages/msix#label-windows-store
  display_name: pedax
  publisher_display_name: Naoki Shimizu
  identity_name: 1781NaokiShimizu.pedax
  msix_version: 1.8.0.0
  publisher: CN=4CCE9711-39B6-4ECC-AA74-A350014A69B0
  languages: en, ja
  logo_path: assets/images/pedax_logo.png
  start_menu_icon_path: assets/images/pedax_logo.png
  tile_icon_path: assets/images/pedax_logo.png
  architecture: x64
