# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:mac)

platform :mac do
  desc "build for app store"
  lane :build_for_app_store do
    # See: https://docs.fastlane.tools/actions/setup_ci/
    setup_ci(provider: "travis") # for keychain

    # See: https://appstoreconnect.apple.com/access/api
    # REF: https://developer.apple.com/videos/play/wwdc2018/303/
    # See: https://docs.fastlane.tools/best-practices/continuous-integration/#method-1-app-store-connect-api-key-recommended
    # See: https://docs.fastlane.tools/actions/app_store_connect_api_key/
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
    )

    # See: Matchfile
    # See: https://docs.fastlane.tools/actions/match
    match(
      api_key: api_key,
      app_identifier: 'com.done.sensuikan1973.pedax',
      type: "appstore",
      readonly: is_ci,
    )

    # See: Appfile
    # See: https://docs.fastlane.tools/actions/build_mac_app/
    build_mac_app(
      workspace: "Runner.xcworkspace",
      configuration: "Release",
      scheme: "Runner",
      clean: true,
      export_team_id: "Z2P4D5D6K2",
      export_method: "app-store",
    )
  end

  desc "deploy app store"
  lane :deploy_app_store do
    # See: https://appstoreconnect.apple.com/apps/1557500142/appstore
    # See: https://docs.fastlane.tools/actions/upload_to_app_store/
    upload_to_app_store(
      pkg: "pedax.pkg",
      automatic_release: true,
      skip_screenshots: true,
      skip_binary_upload: true, # for debug
    )
  end
end
