name: Upgrade Ruby Version

on:
  schedule:
    - cron: '0 1 * * *' # everyday, 01:00 (UTC)
  workflow_dispatch:

jobs:
  upgrade_flutter_dependencies:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: upgrade ruby version
        run: |
          latest_version=$(rbenv install -l | grep -v - | tail -1)
          rbenv install $latest_version
          rbenv local $latest_version

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PAT }}
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: '[Scheduled] upgrade ruby version'
          title: '[Scheduled] upgrade ruby version'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: cron_upgrade_ruby_version
          delete-branch: true
          labels: |
            dependencies
            mac
          assignees: sensuikan1973
          reviewers: sensuikan1973

      # See: https://github.com/peter-evans/create-pull-request/tree/main#auto-merge
      - name: enable auto-merge
        if: steps.create_pull_request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
