# See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
# See: https://github.com/sensuikan1973/pedax/settings/branch_protection_rules/19119198

name: Dependabot auto-merge

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  enbale_auto_merge_on_dependabot_PR:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: enable auto-merge for dependabot PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
