---
name: Flutter Deployment MacOS dry-run

on:
  pull_request:
    paths:
      - 'macos/**'
      - '.ruby-version'
      - 'scripts/deploy_macos_app_to_app_store.sh'
      - '.github/workflows/deploy_macos_dry_run.yaml'
      - 'pubspec.*'
      - 'scripts/setup_flutter.sh'
  push:
    branches: [main]
    paths:
      - 'macos/**'
      - '.ruby-version'
      - 'scripts/deploy_macos_app_to_app_store.sh'
      - '.github/workflows/deploy_macos_dry_run.yaml'
      - 'pubspec.*'
      - 'scripts/setup_flutter.sh'
  workflow_dispatch:

jobs:
  dry_run_macos_deployment:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          cache: true
      - name: setup flutter channel
        shell: zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
        run: ./scripts/setup_flutter.sh
      - name: setup flutter desktop
        shell: zsh {0}
        run: .github/scripts/macos/install_additional_requirements_for_flutter.sh

      - uses: ruby/setup-ruby@v1
      - name: dry-run deployment script
        shell: zsh {0}
        env:
          # https://docs.fastlane.tools/best-practices/continuous-integration/github/
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_KEY_CONTENT_BASE64_ENCODED: ${{ secrets.ASC_KEY_CONTENT_BASE64_ENCODED }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SENTRY_DSN: https://example.com
        run: |
          echo $ZSH_NAME $ZSH_VERSION
          ./scripts/deploy_macos_app_to_app_store.sh \
          -revision "$GITHUB_SHA" --skip-test --dry-run
