---
name: Flutter Deployment MacOS dry-run

on:
  pull_request:
    paths:
      - 'macos/**'
      - '.ruby-version'
      - 'scripts/deploy_macos_app_to_app_store.sh'
      - '.github/workflows/deploy_macos_dry_run.yaml'
      - 'pubspec.*'
      - 'scripts/setup_flutter.sh'
  push:
    branches: [main]
    paths:
      - 'macos/**'
      - '.ruby-version'
      - 'scripts/deploy_macos_app_to_app_store.sh'
      - '.github/workflows/deploy_macos_dry_run.yaml'
      - 'pubspec.*'
      - 'scripts/setup_flutter.sh'
  workflow_dispatch:

jobs:
  dry_run_macos_deployment_script:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: setup flutter channel
        shell: zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
        run: ./scripts/setup_flutter.sh
      - name: setup flutter desktop
        shell: zsh {0}
        run: .github/scripts/macos/install_additional_requirements_for_flutter.sh

      - uses: ruby/setup-ruby@v1
      - name: dry-run deployment script with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: |
            zsh {0}
            echo $ZSH_NAME $ZSH_VERSION
            REVISION=$GITHUB_SHA
            P8_PATH="../README.md" # dummy for dry-run

            ASC_KEY_ID=xxx \
            ASC_ISSUER_ID=xxx \
            APPLE_ID=xxx \
            ITC_TEAM_ID=xxx \
            ./scripts/deploy_macos_app_to_app_store.sh \
            -revision "$REVISION" -p8-file-path "$P8_PATH" -sentry-dsn "https://example.com" \
            --dry-run --skip-test
