name: Flutter Deployment MacOS dry-run

on:
  pull_request:
    paths:
      - 'macos/**'
      - 'scripts/deploy_macos_app_to_app_store.sh'
      - '.github/workflows/deploy_macos_dry_run.yaml'
      - 'pubspec.*'
  push:
    branches: [main]
    paths:
      - 'macos/**'
      - 'scripts/deploy_macos_app_to_app_store.sh'
      - '.github/workflows/deploy_macos_dry_run.yaml'
      - 'pubspec.*'

jobs:
  deployment:
    runs-on: macos-11
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          cache: true
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter_channel.sh
      - name: setup flutter desktop
        shell: bash
        run: .github/scripts/setup_on_macos.sh

      - uses: ruby/setup-ruby@v1
      - name: dry-run deployment script with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: |
            zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
            echo $ZSH_NAME $ZSH_VERSION
            REVISION=$GITHUB_SHA
            P8_PATH="../README.md" # dummy for dry-run
            ./scripts/deploy_macos_app_to_app_store.sh -revision $REVISION -p8-file-path $P8_PATH --dry-run
