---
name: Flutter Deployment MacOS dry-run

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dry_run_macos_deployment:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.19.0
        with:
          cache: true
      - name: setup flutter channel
        shell: zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
        run: ./scripts/setup_flutter.sh
      - name: setup flutter desktop
        shell: zsh {0}
        run: .github/scripts/macos/install_additional_requirements_for_flutter.sh

      - name: bump version
        run: |
          flutter pub get
          dart run cider bump patch --bump-build --pre ci

      - name: git commmit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git add -A
          git commit -m "temporary bump version for ci"

      - uses: ruby/setup-ruby@v1
      - name: dry-run deployment script
        shell: zsh {0}
        env:
          # https://docs.fastlane.tools/best-practices/continuous-integration/github/
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_KEY_CONTENT_BASE64_ENCODED: ${{ secrets.ASC_KEY_CONTENT_BASE64_ENCODED }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SENTRY_DSN: https://example.com
        run: |
          echo $ZSH_NAME $ZSH_VERSION
          ./scripts/deploy_macos_app_to_app_store.sh \
          -revision $(git rev-parse HEAD) --dry-run
