# See: https://flutter.dev/docs/deployment/cd
# See: https://docs.fastlane.tools/actions/build_mac_app/
# REF: https://github.com/flutter/gallery/blob/master/.github/workflows/deploy_play_store.yml

name: Deploy macos app to app store

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
  pull_request: # for debug
    paths: ['.github/workflows/deploy_app_store.yaml', '.github/scripts/**', 'macos/**']

jobs:
  deploy_app_store:
    env:
      ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
      ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
      ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-10.15]
        flutter_channel: [beta]
        mode: [release]
        include:
          - os: macos-10.15
            subcommand: macos
            setup_script: .github/scripts/setup_on_macos.sh
            prepare_to_pack_script: .github/scripts/prepare_to_pack_for_macos.sh

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - name: setup
        shell: bash
        run: ${{ matrix.setup_script }}
      - name: install dependencies
        run: flutter pub get
      - name: doctor
        run: flutter doctor -v
      - name: build
        run: flutter build ${{ matrix.subcommand }} --${{ matrix.mode }}
      - name: prepare to pack
        shell: bash
        run: ${{ matrix.prepare_to_pack_script }}

      - name: output build info
        shell: bash
        run: .github/scripts/output_build_info.sh . && cat env.txt

      - name: setup fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'head'
          bundler-cache: true
          working-directory: macos

      - name: build
        run: fastlane build_for_app_store
      - name: deploy
        run: fastlane deploy_app_store
