name: Flutter CI

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - 'assets/libedax/**'
      - '.github/workflows/flutter_ci.yaml'
      - '.libedax_assets_tag'
      - '.codecov.yml'
  push:
    branches: [main]
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - 'assets/libedax/**'
      - '.github/workflows/flutter_ci.yaml'
      - '.libedax_assets_tag'
      - '.codecov.yml'

jobs:
  format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter format -l 120 --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: install dependencies
        run: flutter pub get
      - run: flutter analyze --fatal-infos --fatal-warnings .

  widget_test:
    needs: [format, analyze]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04] # pedax uses ffi package(libedax4dart), so run widget test on multiple OS.
        flutter_channel: [beta, stable] # stable is debug for https://github.com/sensuikan1973/pedax/pull/260
        include:
          - os: windows-2019
            setup_script: .github/scripts/setup_on_windows.sh
          - os: macos-11
            setup_script: .github/scripts/setup_on_macos.sh
          - os: ubuntu-20.04
            setup_script: .github/scripts/setup_on_linux.sh

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - name: setup flutter
        shell: bash
        run: ${{ matrix.setup_script }}
      - name: doctor
        run: flutter doctor -v
      - name: install dependencies
        run: flutter pub get
      - name: run test with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: flutter test --concurrency=1 --verbose --coverage --coverage-path=./coverage/lcov.info
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage/lcov.info
