# NOTE: Experimental Job. See: https://flutter.dev/desktop#distribution
# REF: https://github.com/google/flutter-desktop-embedding/blob/master/.github/workflows/ci.yml

name: Flutter Build

on:
  pull_request:
    paths: ['**.dart','pubspec.*', '.github/workflows/flutter_build.yaml', 'macos/**', 'linux/**', 'windows/**', 'assets/**']
  push:
    branches: [main]
    paths: ['**.dart','pubspec.*', '.github/workflows/flutter_build.yaml', 'macos/**', 'linux/**', 'windows/**', 'assets/**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false # I want results from all OSes even if one fails.
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        flutter_channel: [dev, beta]
        mode: [release]
        include: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - os: ubuntu-20.04
            subcommand: linux
            setup-script: |-
              flutter config --enable-linux-desktop
              sudo apt-get update -y
              sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
            postbuild-script: echo "do nothing"
            distribution_path: build/linux/x64/_mode_
          - os: windows-2019
            subcommand: windows
            setup-script: flutter config --enable-windows-desktop
            postbuild-script: |-
              # See: https://flutter.dev/desktop#windows
              target_dll_path=/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Redist/MSVC/14.28.29325/x64/Microsoft.VC142.CRT
              cp $target_dll_path/vcruntime140.dll build/windows/runner/Relelease/vcruntime140.dll
              cp $target_dll_path/vcruntime140_1.dll build/windows/runner/Relelease/vcruntime140_1.dll
              cp $target_dll_path/msvcp140.dll build/windows/runner/Relelease/msvcp140.dll
            distribution_path: build/windows/runner/_mode_
          - os: macos-10.15
            subcommand: macos
            setup-script: flutter config --enable-macos-desktop
            postbuild-script: echo "do nothing"
            distribution_path: build/macos/Build/Products/_mode_

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - name: setup
        run: ${{ matrix.setup-script }}
      - name: install dependencies
        run: flutter pub get
      - name: doctor
        run: flutter doctor -v
      - name: build
        run: flutter build ${{ matrix.subcommand }} --${{ matrix.mode }}

      - name: set output path
        shell: bash
        run: |-
          path=$(echo ${{ matrix.distribution_path }} | sed -e 's/_mode_/${{ matrix.mode }}/g')
          echo "artifact_target=$path" >> $GITHUB_ENV

      - name: output build info
        run: .github/scripts/output_build_info.sh ${{ env.artifact_target }}

      # - name: debug
      #   uses: mxschmitt/action-tmate@v3

      - name: postbuid script
        run: ${{ matrix.postbuild-script }}

      - uses: actions/upload-artifact@v2
        with:
          name: pedax-${{ runner.os }}-${{ matrix.mode }}
          path: ${{ env.artifact_target }}
