# See: https://flutter.dev/desktop#distribution
# REF: https://github.com/google/flutter-desktop-embedding/blob/master/.github/workflows/ci.yml

name: Flutter Build

on:
  pull_request:
    paths-ignore:
      - '**.dart'
      - 'pubspec.*'
      - '.github/workflows/flutter_build.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
  push:
    branches: [main]
    paths-ignore:
      - '**.dart'
      - 'pubspec.*'
      - '.github/workflows/flutter_build.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
  workflow_dispatch:

jobs:
  flutter_build_desktop_app:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: 'echo "passed See: .github/workflows/README.md" '
