name: Flutter CI

on:
  pull_request:
    paths-ignore:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/flutter_ci.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.codecov.yml'
  push:
    branches: [main]
    paths-ignore:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/flutter_ci.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.codecov.yml'
  workflow_dispatch:

jobs:
  flutter_format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: 'echo "passed See: .github/workflows/README.md" '
