name: Flutter Integration Test

on:
  pull_request:
    paths: ['**.dart', 'pubspec.*', '.github/workflows/flutter_integration_test.yaml', '.github/scripts/**', 'macos/**', 'linux/**', 'windows/**', 'assets/**']
  push:
    branches: [main]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/flutter_integration_test.yaml', '.github/scripts/**', 'macos/**', 'linux/**', 'windows/**', 'assets/**']

jobs:
  integration_test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false # I want results from all OSes even if one fails.
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-20.04] # TODO: https://github.com/sensuikan1973/pedax/issues/7
        flutter_channel: [beta]
        include:
          - os: ubuntu-20.04
            device: linux
            setup_script: .github/scripts/setup_on_linux.sh
          - os: windows-2019
            device: windows
            setup_script: .github/scripts/setup_on_windows.sh
          - os: macos-10.15
            device: macos
            setup_script: .github/scripts/setup_on_macos.sh

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - name: setup
        shell: bash
        run: ${{ matrix.setup_script }}
      - name: install dependencies
        run: flutter pub get
      - name: doctor
        run: flutter doctor -v
      - name: drive
        run: flutter drive --driver integration_test/driver.dart --target integration_test/app_test.dart -d ${{ matrix.device }}
