name: Flutter Integration Test

on:
  pull_request:
    paths: ['**.dart', 'pubspec.*', '.github/workflows/flutter_integration_test.yaml', 'macos/**', 'linux/**', 'windows/**', 'assets/**']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/flutter_integration_test.yaml', 'macos/**', 'linux/**', 'windows/**', 'assets/**']

jobs:
  integration_test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false # I want results from all OSes even if one fails.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - os: ubuntu-latest
            device: linux
            setup-script: |-
              flutter config --enable-linux-desktop
              sudo apt-get update
              sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
          - os: windows-latest
            device: windows
            setup-script: flutter config --enable-windows-desktop
          - os: macos-latest
            device: macos
            setup-script: flutter config --enable-macos-desktop

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: setup
        run: ${{ matrix.setup-script }}
      - name: install dependencies
        run: flutter pub get
      - name: doctor
        run: flutter doctor -v
      - name: drive
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 600
          max_attempts: 3
          retry_on: error
          command: flutter drive --driver integration_test/driver.dart --target integration_test/app_test.dart -d ${{ matrix.device }}
