name: Flutter CI

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - 'assets/libedax/**'
      - '.github/workflows/flutter_ci.yaml'
      - '.libedax_assets_tag'
      - '.codecov.yml'
  push:
    branches: [main]
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - 'assets/libedax/**'
      - '.github/workflows/flutter_ci.yaml'
      - '.libedax_assets_tag'
      - '.codecov.yml'

jobs:
  format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter format -l 120 --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: install dependencies
        run: flutter pub get
      - run: flutter analyze --fatal-infos --fatal-warnings .

  widget_test:
    needs: [format, analyze]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false # I want results from all OSes even if one fails.
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04]
        flutter_channel: [beta]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - name: doctor
        run: flutter doctor -v
      - name: install dependencies
        run: flutter pub get
      - name: run test
        run: flutter test --concurrency 1 --coverage --coverage-path=./coverage/lcov.info
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage/lcov.info
