---
name: Flutter CI

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/flutter_ci.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.codecov.yml'
      - 'scripts/setup_flutter.sh'
  push:
    branches: [main]
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/flutter_ci.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.codecov.yml'
      - 'scripts/setup_flutter.sh'
  workflow_dispatch:

jobs:
  flutter_format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.4.0
        with:
          cache: true
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter.sh
      - run: flutter format -l 120 --set-exit-if-changed .

  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.4.0
        with:
          cache: true
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter.sh
      - name: install dependencies
        run: flutter pub get
      - run: flutter analyze --fatal-infos --fatal-warnings .

  flutter_tests:
    needs: [flutter_format, flutter_analyze]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] # pedax uses ffi package(libedax4dart), so run widget test on multiple OS.
        include:
          - os: windows-latest
            setup_for_flutter_desktop_script: .github/scripts/windows/install_additional_requirements_for_flutter.sh
            integration_test_command: flutter test integration_test --verbose
          - os: macos-latest
            setup_for_flutter_desktop_script: .github/scripts/macos/install_additional_requirements_for_flutter.sh
            integration_test_command: flutter test integration_test --verbose
          - os: ubuntu-latest
            setup_for_flutter_desktop_script: .github/scripts/linux/install_additional_requirements_for_flutter.sh
            integration_test_command: 'timeout 180 xvfb-run -a flutter test integration_test --verbose || ( [[ $? -eq 124 ]] && echo "WARNING: timeout" )'
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.4.0
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter.sh
      - name: setup flutter desktop
        shell: bash
        run: ${{ matrix.setup_for_flutter_desktop_script }}
      - name: doctor
        run: flutter doctor -v
      - name: install dependencies
        run: flutter pub get
      - name: run widget test with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: flutter test --concurrency=1 --verbose --coverage --coverage-path=./coverage/lcov.${{ matrix.os }}.info
      - name: run integration test with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: ${{ matrix.integration_test_command }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./coverage/lcov.${{ matrix.os }}.info

  # See: https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/
  upload_coverage_report_to_codecov:
    needs: [flutter_tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.windows-latest.info,./coverage/lcov.macos-latest.info,./coverage/lcov.ubuntu-latest.info
