name: Flutter Integration Test

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - '.github/workflows/flutter_integration_test.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.libedax_assets_tag'
  push:
    branches: [main]
    paths:
      - '**.dart'
      - 'pubspec.*'
      - '.github/workflows/flutter_integration_test.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.libedax_assets_tag'

jobs:
  integration_test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false # I want results from all OSes even if one fails.
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04]
        flutter_channel: [beta]
        include:
          - os: windows-2019
            device: windows
            setup_script: .github/scripts/setup_on_windows.sh
          - os: macos-11
            device: macos
            setup_script: .github/scripts/setup_on_macos.sh
          - os: ubuntu-20.04
            device: linux
            setup_script: .github/scripts/setup_on_linux.sh

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - name: setup flutter
        shell: bash
        run: ${{ matrix.setup_script }}
      - name: doctor
        run: flutter doctor -v
      - name: install dependencies
        run: flutter pub get
      - name: debug build and run
        if: runner.os == 'Linux'
        run: |
          export DISPLAY="${DISPLAY:-:0}"
          flutter run -d linux --debug
      - name: drive
        run: flutter drive --driver integration_test/driver.dart --target integration_test/app_test.dart -d ${{ matrix.device }}
