---
name: Flutter CI

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/flutter_ci.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.codecov.yml'
      - 'scripts/setup_flutter.sh'
  push:
    branches: [main]
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/flutter_ci.yaml'
      - '.github/scripts/**'
      - 'macos/**'
      - 'linux/**'
      - 'windows/**'
      - 'assets/**'
      - '.codecov.yml'
      - 'scripts/setup_flutter.sh'
  workflow_dispatch:

jobs:
  # https://docs.flutter.dev/development/tools/formatting
  flutter_format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter.sh
      - run: flutter format -l 120 --set-exit-if-changed .

  # https://docs.flutter.dev/reference/flutter-cli#flutter-commands
  # https://flutter.dev/docs/development/tools/flutter-fix#applying-project-wide-fixes
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter.sh
      - name: install dependencies
        run: flutter pub get
      # - run: flutter analyze --fatal-infos --fatal-warnings .

  # https://docs.flutter.dev/testing
  flutter_tests:
    needs: [flutter_format, flutter_analyze]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      # fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] # pedax uses ffi package(libedax4dart), so run widget test on multiple OS.
        include:
          - os: windows-latest
            setup_for_flutter_desktop_script: .github/scripts/windows/install_additional_requirements_for_flutter.sh
            integration_test_command: flutter test integration_test --verbose --coverage --coverage-path=./coverage/lcov.integration_test.info
          - os: macos-latest
            setup_for_flutter_desktop_script: .github/scripts/macos/install_additional_requirements_for_flutter.sh
            integration_test_command: flutter test integration_test --verbose --coverage --coverage-path=./coverage/lcov.integration_test.info
          - os: ubuntu-latest
            setup_for_flutter_desktop_script: .github/scripts/linux/install_additional_requirements_for_flutter.sh
            integration_test_command: |
              touch ./coverage/lcov.integration_test.info
              timeout 240 xvfb-run -a \
              flutter test integration_test --verbose --coverage --coverage-path=./coverage/lcov.integration_test.info \
              || ( [[ $? -eq 124 ]] && echo "WARNING: timeout" )
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: setup flutter channel
        shell: bash
        run: ./scripts/setup_flutter.sh
      - name: setup flutter desktop
        shell: bash
        run: ${{ matrix.setup_for_flutter_desktop_script }}
      - name: doctor
        run: flutter doctor -v
      - name: install dependencies
        run: flutter pub get

      # https://docs.flutter.dev/testing#widget-tests
      - name: run widget test with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: flutter test --concurrency=1 --coverage --coverage-path=./coverage/lcov.widget_test.info
      # https://docs.codecov.com/docs/merging-reports#multiple-languages
      - uses: codecov/codecov-action@v3
        with: # ref: https://github.com/codecov/codecov-action/blob/v3.1.0/.github/workflows/main.yml
          files: ./coverage/lcov.widget_test.info
          flags: widget_test,${{ matrix.os }}
          fail_ci_if_error: true
          # See: https://github.com/codecov/codecov-action/issues/837
          # https://app.codecov.io/gh/sensuikan1973/pedax/settings
          token: ${{ secrets.CODECOV_TOKEN }}

      # https://docs.flutter.dev/testing#integration-tests
      - name: run integration test with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: ${{ matrix.integration_test_command }}
      # https://docs.codecov.com/docs/merging-reports#multiple-languages
      - uses: codecov/codecov-action@v3
        with: # ref: https://github.com/codecov/codecov-action/blob/v3.1.0/.github/workflows/main.yml
          files: ./coverage/lcov.integration_test.info
          flags: integration_test,${{ matrix.os }}
          fail_ci_if_error: true
          # See: https://github.com/codecov/codecov-action/issues/837
          # https://app.codecov.io/gh/sensuikan1973/pedax/settings
          token: ${{ secrets.CODECOV_TOKEN }}
