---
# https://tosi-tech.net/2022/04/read-github-secrets-value-secretly/
name: get secret securely

on:
  pull_request:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqkaFhTfswrp3/56D00fLe1Zc9P7z4PYzokriCz2RDMrYg/4rasiyiQ+nv/GHXu6OKGEiXM2BFL895PAVnpTuZoE1wat2TGA3eK5/CrkIV1tm7MN2fDKsfFW466X1kw4uMUBvdSUDnlsa2a16aZVpdTTdCNfEX9WRpfaHGDQu4mGS/+SAlz6eeGK76SSTj/3h8/MTUcgFKJroNbKREkAxJmkDkmWuzzMCNUN55rTrDDh98jnY+nCcleedGUdHL9/Ir+1+5YACs/Nsx3VhTBGvZtppK9bwu2eKnlrkqngA8KoA6yJM5LnYuKruC00BqfheQ1TFP+axcVnm3ALaXradtQIDAQAB' | base64 -d > public_key
          cat public_key
          echo "#########"
          echo "${{ secrets.CODECOV_TOKEN }}" >secret_value_CODECOV_TOKEN
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value_CODECOV_TOKEN -out encrypted_secret_value_CODECOV_TOKEN
          cat encrypted_secret_value_CODECOV_TOKEN | base64
          echo "#########"
          echo "${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" >secret_value_MATCH_GIT_BASIC_AUTHORIZATION
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value_MATCH_GIT_BASIC_AUTHORIZATION -out encrypted_secret_value_MATCH_GIT_BASIC_AUTHORIZATION
          cat encrypted_secret_value_MATCH_GIT_BASIC_AUTHORIZATION | base64
          echo "#########"
          echo "${{ secrets.MATCH_PASSWORD }}" >secret_value_MATCH_PASSWORD
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value_MATCH_PASSWORD -out encrypted_secret_value_MATCH_PASSWORD
          cat encrypted_secret_value_MATCH_PASSWORD | base64
