---
# https://tosi-tech.net/2022/04/read-github-secrets-value-secretly/
name: get secret securely

on:
  pull_request:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnf6lJ9+I11K4K0eYiyNC7YITXFBC66S0khOl5kdSZBtDICzNnnszyVJSxYgABqHsqB6VlifVlYlN42w0Ow4EPkZX07w4EVaGQjDI+B4phaJg+FdcCqLXDGyPFbeE+nPNnxktRWXDg9C2l9pGSbdXX2ONgeNajjTSLpRAPoh06pvCeXVO7jx3kMR60PP1QiLZJSz7wh7xuJ+V35wGYzG2N+2s8765MEUgbb5y5q+H7jNjgON7M+5Uie9Hef67pvXdoB3NJ5KXcdkNhM0tFmKN5jzhtK/vO9D6nf6650wPMp31ChFHqsnkWNAClc+6QLUTsJVbb/rPl64QP8fl2auuWQIDAQAB' | base64 -d > public_key
          cat public_key
          echo "#########"
          echo "${{ secrets.CODECOV_TOKEN }}" >secret_value_CODECOV_TOKEN
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value_CODECOV_TOKEN -out encrypted_secret_value_CODECOV_TOKEN
          cat encrypted_secret_value_CODECOV_TOKEN | base64
          echo "#########"
          echo "${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" >secret_value_MATCH_GIT_BASIC_AUTHORIZATION
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value_MATCH_GIT_BASIC_AUTHORIZATION -out encrypted_secret_value_MATCH_GIT_BASIC_AUTHORIZATION
          cat encrypted_secret_value_MATCH_GIT_BASIC_AUTHORIZATION | base64
          echo "#########"
          echo "${{ secrets.MATCH_PASSWORD }}" >secret_value_MATCH_PASSWORD
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value_MATCH_PASSWORD -out encrypted_secret_value_MATCH_PASSWORD
          cat encrypted_secret_value_MATCH_PASSWORD | base64
