name: Shell Script CI

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell_ci.yaml'
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - '.github/workflows/shell_ci.yaml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
