name: Shell Script CI

on:
  pull_request:
    paths-ignore:
      - '**/*.sh'
      - '.github/workflows/shell_script_ci.yaml'
  push:
    branches: [main]
    paths-ignore:
      - '**/*.sh'
      - '.github/workflows/shell_script_ci.yaml'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: 'echo "passed See: .github/workflows/README.md" '
