name: Shell Script CI

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell_ci.yaml'
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - '.github/workflows/shell_ci.yaml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        with:
          # See: https://github.com/koalaman/shellcheck/issues/809
          # zsh is not supported.
          ignore_names: deploy_macos_app_to_app_store.sh fetch_libedax_assets.sh
