name: Shell Script CI

on:
  pull_request:
    paths-ignore:
      - '**/*.sh'
      - '.github/workflows/shell_script_ci.yaml'
  push:
    branches: [main]
    paths-ignore:
      - '**/*.sh'
      - '.github/workflows/shell_script_ci.yaml'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/always_success
