name: Upgrade Website Dependencies

on:
  schedule:
    - cron: '0 1 * * *' # everyday, 01:00 (UTC)
  workflow_dispatch:

jobs:
  upgrade_flutter_dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: upgrade website deps
        working-directory: website
        run: |
          yarn upgrade
          yarn upgrade --latest --scope=@docusaurus

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        uses: peter-evans/create-pull-request@v4
        with:
          # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PAT }}
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: '[Scheduled] upgrade website dependencies'
          title: '[Scheduled] upgrade website dependencies'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: cron_upgrade_website_dependencies
          delete-branch: true
          labels: |
            dependencies
            website
          assignees: sensuikan1973
          reviewers: sensuikan1973
