# See: https://docusaurus.io/docs/deployment#deploying-to-github-pages

name: Build Website

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/website_build.yaml'
      - 'website/**'
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/website_build.yaml'
      - 'website/**'
  workflow_dispatch:

jobs:
  build_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/do_nothing_on_counterpart_workflow.sh
