---
name: Upgrade Website Dependencies

on:
  schedule:
    - cron: '0 21 * * *' # everyday, 21:00 (UTC)
  workflow_dispatch:

jobs:
  upgrade_flutter_dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node/issues/206#issuecomment-774538395
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'

      - name: upgrade website deps
        working-directory: website
        run: |
          yarn upgrade
          yarn upgrade --latest --scope=@docusaurus

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PAT }}
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: '[Scheduled] upgrade website dependencies'
          title: '[Scheduled] upgrade website dependencies'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: cron_upgrade_website_dependencies
          delete-branch: true
          labels: |
            dependencies
            website

      # See: https://github.com/peter-evans/create-pull-request/tree/main#auto-merge
      - name: enable auto-merge
        if: steps.create_pull_request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
